# Generated by Django 4.1.4 on 2023-01-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_user_alter_project_owner'),
        ('users', '0004_user_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
