# Generated by Django 4.1.4 on 2023-01-10 18:52

from django.db import migrations, models
import django.db.models.deletion
import projects.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_user_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('demo_link', models.URLField()),
                ('vote_ration', models.DecimalField(decimal_places=1, max_digits=2)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(default=projects.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.user')),
            ],
        ),
    ]
