# Generated by Django 4.1.4 on 2023-01-16 15:19

from django.db import migrations, models
import django.db.models.deletion
import projects.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_owner_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=projects.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.user'),
        ),
    ]
