# Generated by Django 4.1.4 on 2023-01-17 18:04

from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_alter_profile_user'),
        ('projects', '0017_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=users.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
