# Generated by Django 4.1.4 on 2023-03-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True),
        ),
    ]
