# Generated by Django 4.1.4 on 2023-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vote_ration',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
